### ISSUE TITLE
inputs in complex cosmic population function

### ISSUE THREAD

**Issue by KshitijAggarwal** [davidgardenier/frbpoppy#41]
The following in the complex function under `cosmic_pop.py`
https://github.com/davidgardenier/frbpoppy/blob/ccaf4869965cb752e78d55d1c02afa64e9467c0e/frbpoppy/cosmic_pop.py#L531 should be `repeaters=repeaters, generate=generate)` as otherwise, it won't use the inputs of the function for the population.

**Comment by davidgardenier** [comment]
Fixed :+1: Note that this doesn't change much, as this only sets a argument to true in the cosmic population. If you check further down in the functions, I use the repeaters and generate keyword arguments at a different stage, and they should not both be invoked at the earlier stage.
